### ISSUE TITLE
Temporary table is used outside of its own session

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#1039]
Podczas debugowania [tego wątku](https://forum.opencaching.pl/viewtopic.php?p=137673&sid=2ffbf8ef0de63887f22657d4a8c1f9be#p137684) udało mi się wywołać taki błąd:

```
[Tue Jun 13 19:26:04.479804 2017] [:error] [pid 10816] [client 89.71.202.200:65165]
PHP Fatal error:
Uncaught exception 'PDOException' with message
'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ocpldb.result_caches' doesn't exist'
in /srv/ocpl/lib/search.jsoncodes.inc.php:18
Stack trace:
#0 /srv/ocpl/lib/search.jsoncodes.inc.php(18): PDO->query('\\n    select wp_...', 7, 0)
#1 /srv/ocpl/search.php(1151): require('/srv/ocpl/lib/s...')
#2 {main}
thrown in /srv/ocpl/lib/search.jsoncodes.inc.php on line 18
```

No i faktycznie. Tabela 'ocpldb.result_caches` nie istnieje (patrząc na aktualny [dbsctruct](https://opencaching.pl/okapi/devel/dbstruct)). A mimo wszystko pojawiają się do niej odwołania w kodzie. Wtf?

**Comment by wrygiel** [comment]
@deg-pl, to prawdopodobnie jest powód przez który pokazało Ci się HTTP 500 [tutaj](https://forum.opencaching.pl/viewtopic.php?p=137673&sid=2ffbf8ef0de63887f22657d4a8c1f9be#p137684).

**Comment by wrygiel** [comment]
Zrobiłem grepa po kodzie i okazuje się, że to jest "temporary table". Z dokumentacji:

> A TEMPORARY table is visible only to the current session, and is dropped automatically when the session is closed.

A zatem problem pewnie wynika z tego, że tabela jest tworzona w jednej sesji, a potem robiony jest SELECT na innej sesji (mimo, że w ramach obsługi tego samego requesta).
