### ISSUE TITLE
Badges module generates error while removing log

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1097]
On my devel machine (and OC UK also) I give error when removing "found" log. I have no badges table.

Error from OC UK:

```
[Thu Jul 20 22:46:24.539096 2017] [php7:warn] [pid 9811] [client 46.134.165.116:4069] PHP Warning:  OcPdo Error: Query: SELECT\r\n                badges.id badges_id,\r\n                badges.trigger_type badges_trigger_type,\r\n                badges.belonging_query badges_belonging_query,\r\n                badges.gained_query badges_gained_query\r\n\n                FROM badges  WHERE trigger_type=2. Trace:  | /srv/ocuk/Utils/Database/OcDb.php::140 | /srv/ocuk/lib/Controllers/MeritBadgeController.php::230 | /srv/ocuk/lib/Controllers/MeritBadgeController.php::160 | /srv/ocuk/lib/Controllers/LogEnteryController.php::60 | /srv/ocuk/lib/Controllers/LogEnteryController.php::20 | /srv/ocuk/Controllers/CacheLogController.php::35 | /srv/ocuk/removelog.php::8 in /srv/ocuk/Utils/Database/OcPdo.php on line 113, referer: https://opencache.uk/viewcache.php?cacheid=66
[Thu Jul 20 22:46:24.539333 2017] [php7:notice] [pid 9811] [client 46.134.165.116:4069] Db message:SQLSTATE[42S22]: Column not found: 1054 Unknown column 'badges.belonging_query' in 'field list', referer: https://opencache.uk/viewcache.php?cacheid=66
[Thu Jul 20 22:46:24.539488 2017] [php7:warn] [pid 9811] [client 46.134.165.116:4069] PHP Warning:  OcPdo Error: . Trace:  | /srv/ocuk/lib/Controllers/MeritBadgeController.php::258 | /srv/ocuk/lib/Controllers/MeritBadgeController.php::231 | /srv/ocuk/lib/Controllers/MeritBadgeController.php::160 | /srv/ocuk/lib/Controllers/LogEnteryController.php::60 | /srv/ocuk/lib/Controllers/LogEnteryController.php::20 | /srv/ocuk/Controllers/CacheLogController.php::35 | /srv/ocuk/removelog.php::8 in /srv/ocuk/Utils/Database/OcPdo.php on line 113, referer: https://opencache.uk/viewcache.php?cacheid=66
[Thu Jul 20 22:46:24.539554 2017] [php7:notice] [pid 9811] [client 46.134.165.116:4069] Db message:Utils\\Database\\OcDb::rowCount: call PDOstatement issue!, referer: https://opencache.uk/viewcache.php?cacheid=66
```

**Comment by deg-pl** [comment]
@tripper1971 - metoda getMeritBadgeQuery() odwołuje się m.in. do badges.belonging_query i badges.gained_query, a tych pól nie ma w bazie danych - wprowadziłeś je chyba ręcznie do OC PL, ale inne nody nie mają i sypią błędami. Z tego co widzę, jedyny alter bazy to 2017-03-30_merit_badges.sql i nie ma tych pól tam. Przygotuj proszę odpowiedniego sqlAltera modyfikującego strukturę bazy.

**Comment by tripper1971** [comment]
I prepared a new file (2017-08-31 merit badges.sql).
I implemented a flag meritBadges. If it is set turned off, getMeritBadgeQuery() should not be called.
I will check it in next week.

**Comment by deg-pl** [comment]
@tripper1971 Should we first DROP all badge* tables and next to run 2017-08-31_merit_badges.sql?

Have the PL node right DB structure already?

**Comment by tripper1971** [comment]
Have the PL node right DB structure already?
since 2 months

"Should we first DROP all badge* tables and next to run 2017-08-31_merit_badges.sql?"
yes, in other nodes

**Comment by deg-pl** [comment]
@tripper1971 flag meritBadges is not respected while removing the log

```
+++ Ex_Msg: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ocuk-new.badges' doesn't exist
+++ Ex_Trace:
#0 /srv/ocpl/Utils/Database/OcDb.php(155): PDOStatement->execute()
#1 /srv/ocpl/lib/Controllers/MeritBadgeController.php(230): Utils\Database\OcDb->simpleQuery('SELECT\r\n       ...')
#2 /srv/ocpl/lib/Controllers/MeritBadgeController.php(160): lib\Controllers\MeritBadgeController->buildArrayMeritBadgesTriggerLogs()
#3 /srv/ocpl/lib/Controllers/LogEnteryController.php(62): lib\Controllers\MeritBadgeController->updateCurrValUserMeritBadges(920, 104318)
#4 /srv/ocpl/lib/Controllers/LogEnteryController.php(22): lib\Controllers\LogEnteryController->removeLog(Object(lib\Objects\GeoCache\GeoCacheLog), NULL)
#5 /srv/ocpl/Controllers/CacheLogController.php(35): lib\Controllers\LogEnteryController->removeLogById(3430)
#6 /srv/ocpl/removelog.php(8): Controllers\CacheLogController->removeLog()
#7 {main}
```

Celowo usunąłem tabele, aby wychwycić błędy. Przy dodawaniu logów wszystko jest OK, przy usuwaniu - sypie błędami jak powyżej.
Po dodaniu tabel z Twojego najnowszego sqlalter problem znika, ale to chyba nie tak powinno działać.

**Comment by andrixnet** [comment]
`2017-08-31_merit_badges.sql` deployed at OCRO after first dropping pre-existing `badge*` tables.
(we don't use merit badges, yet).

**Comment by tripper1971** [comment]
As I wrote, in next week I will look at the code.
If I understand, in this case (ocuk), the flag: meritBadges is set to false (?)

**Comment by deg-pl** [comment]
Error log was from my devel site. On devel site (and OC UK) there is no meritBadges flag in settings.inc.php, but settingsDefault.inc.php sets this flag to false.

**Comment by tripper1971** [comment]
done
