### ISSUE TITLE
Minor errors in code (exceptions) again

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1982]
ErrorException: Undefined variable: result

#0 /srv/ocpl/newcacheAjaxWaypointUploader.php(93): src\Utils\Debug\ErrorHandler::handleError(8, 'Undefined varia...', '/srv/ocpl/newca...', 93, Array)

#1 {main}

**Comment by kojoty** [comment]
ErrorException: Undefined index: powerTrailId

#0 /srv/ocuk/powerTrail/ajaxImage.php(11): src\Utils\Debug\ErrorHandler::handleError(8, 'Undefined index...', '/srv/ocuk/power...', 11, Array)

#1 {main}

**Comment by kojoty** [comment]
ErrorException: Undefined index: user_id

#0 /srv/ocpl/powerTrail/powerTrailController.php(65): src\Utils\Debug\ErrorHandler::handleError(8, 'Undefined index...', '/srv/ocpl/power...', 65, Array)
#1 /srv/ocpl/powerTrail/powerTrailController.php(37): powerTrailController->mySeries()
#2 /srv/ocpl/powerTrail.php(145): powerTrailController->run()
#3 {main}

**Comment by kojoty** [comment]
ErrorException: imagecreatefromjpeg(/srv/ocuk/src/Controllers/../../public/images/qrcode_bg.jpg): failed to open stream: No such file or directory

#0 [internal function]: src\Utils\Debug\ErrorHandler::handleError(2, 'imagecreatefrom...', '/srv/ocuk/src/C...', 89, Array)
#1 /srv/ocuk/src/Controllers/UserUtilsController.php(89): imagecreatefromjpeg('/srv/ocuk/src/C...')
#2 [internal function]: src\Controllers\UserUtilsController->qrCodeGen()
#3 /srv/ocuk/src/Utils/Uri/SimpleRouter.php(112): call_user_func_array(Array, Array)
#4 /srv/ocuk/public/index.php(8): src\Utils\Uri\SimpleRouter::run()
#5 {main}

**Comment by kojoty** [comment]
Got error 'PHP message: Unknown translation for id: image_err_no_desc

**Comment by kojoty** [comment]
ErrorException: Undefined index: country

#0 /srv/ocuk/newcachesrest.php(53): src\Utils\Debug\ErrorHandler::handleError(8, 'Undefined index...', '/srv/ocuk/newca...', 53, Array)

#1 {main}

**Comment by kojoty** [comment]
All above should be fixed now.
