### ISSUE TITLE
ErrorException: Undefined offset: 12

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2074]
After solving many other problems, I keep getting these at OCNA server.
```
ErrorException: Undefined offset: 12



#0 /path/to/oc_us/oc/lib/myn.inc.php(75): src\Utils\Debug\ErrorHandler::handleError(8, 'Undefined offse...', '/path/to/oc_u...', 75, Array)

#1 /path/to/oc_us/oc/newcaches.php(120): myninc::checkCacheStatusByUser(Array, NULL)

#2 {main}
```
I am at a loss PHP-wise

**Comment by kojoty** [comment]
It seems that there is not cache type icon ==12 in /lib/cache.php

I can fix it but after the weekend. Now I'm again on the trip...

**Comment by andrixnet** [comment]
I'll tend to it (at least the graphics) early this week.
It is seems directly related to https://github.com/opencaching/opencaching-pl/issues/860 and https://github.com/opencaching/opencaching-pl/issues/2024
