### ISSUE TITLE
SQL error while posting OCTEAM comment and blocking a cache

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2160]
The error occured likely because of unescaped single apostrophe '

```
PDOException: Query|Params: UPDATE cache_desc SET

                rr_comment = CONCAT('<span class="ocTeamCommentHeader">Date: 2020-04-07 21:27, add by TermiteHunter:</span><span class="ocTeamComment">I'm afraid I am not going to be able to list this one here for a couple reasons.<br />

[...]

</span>', rr_comment),

                last_modified = NOW()

            WHERE cache_id= :1  | 2972

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'afraid I am not going to be able to list this one here for a couple reasons.<br ' at line 2



#0 /src/Utils/Database/OcDb.php(443): src\Utils\Database\OcPdo->error('Query|Params: U...', Object(PDOException))

#1 /src/Models/GeoCache/GeoCacheDesc.php(148): src\Utils\Database\OcDb->multiVariableQuery('UPDATE cache_de...', 2972)

#2 /src/Controllers/ViewCacheController.php(83): src\Models\GeoCache\GeoCacheDesc::UpdateAdminComment(Object(src\Models\GeoCache\GeoCache), 'I'm afraid I am...', Object(src\Models\User\User))

#3 [internal function]: src\Controllers\ViewCacheController->saveOcTeamComments('2972')

#4 /src/Utils/Uri/SimpleRouter.php(151): call_user_func_array(Array, Array)

#5 /public/index.php(8): src\Utils\Uri\SimpleRouter::run()

#6 {main}
```

**Comment by mzylowski** [comment]
@rapotek if your commit `735f6f7` fixes this, can we merge it?

**Comment by rapotek** [comment]
> @rapotek if your commit `735f6f7` fixes this, can we merge it?

It is tested and works on my dev environment, so feel free to use it. I just don't create PRs any more.
