### ISSUE TITLE
Duplicate "find" entry

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#535]
See [OP00E3](http://opencaching.pl/viewcache.php?cacheid=227), log of user "ziom97"

**Comment by kojoty** [comment]
nie jestem pewien, ale na mojej developerce można dodać kolejny wpis "znaleziona" przez serwis mobilny.

Nie mogę tez odnaleźć w access-logu miejsca gdzie były zrobione wpisy ziom97, ale może kiepsko szukałem...

**Comment by deg-pl** [comment]
Faktycznie - u mnie też. Można dodać dowolnie dużo "znalezień" tej samej skrzynki.

**Comment by kojoty** [comment]
do tego jesli przyznasz rekomendację to jest jakiś kwas wokół 
`require_once( $rootpath . 'okapi/facade.php');`  (logentry.php:133)

bo przynajmniej na mojej dev. $rootpath nie jest ustawione ,a jak ustawie to dostaję:

```
Oops... Something went wrong on *our* part.

Message was passed on to the site administrators. We'll try to fix it.
Contact the developers if you think you can help!

BUT! Since the DEBUG flag is on, then you probably ARE a developer yourself.
Let's cut to the chase then:

===== ERROR MESSAGE =====
SQL Error 1205: Lock wait timeout exceeded; try restarting transaction

The query was:

            update cache_logs
            set okapi_syncbase = now()
            where
                cache_id = '2271'
                and user_id = '28054'
=========================

--- Stack trace ---
#0 /srv/ocpl/okapi/core.php(490): okapi\Db::query('?            up...')
#1 /srv/ocpl/okapi/facade.php(145): okapi\Db::execute('?            up...')
#2 /srv/ocpl/mobile/logentry.php(135): okapi\Facade::schedule_user_entries_check('2271', '28054')
#3 {main}

--- OKAPI method called ---
/logentry.php
?wp=OP08DD

--- OKAPI version ---
1270 (187a9de9d26929b8a49c34a754a611d5171ab0a5)

--- Request headers ---
Host: local.m.opencaching.pl
Connection: keep-alive
Content-Length: 108
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Origin: http://local.m.opencaching.pl
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Referer: http://local.m.opencaching.pl/logentry.php?wp=OP08DD
Accept-Encoding: gzip, deflate
Accept-Language: pl,en-US;q=0.8,en;q=0.6
Cookie: PHPSESSID=pnho5lm3q9n7dfmi7k76g97tu3; ocpldata=YToyNDp7czo2OiJ1c2VyaWQiO2k6MDtzOjg6InVzZXJuYW1lIjtzOjA6IiI7czo5OiJwZXJtYW5lbnQiO2k6MTtzOjk6Imxhc3Rsb2dpbiI7czowOiIiO3M6OToic2Vzc2lvbmlkIjtzOjA6IiI7czo1OiJhZG1pbiI7aTowO3M6NDoibGFuZyI7czoyOiJwbCI7czo1OiJzdHlsZSI7czo4OiJzdGRzdHlsZSI7czoxMToibGFzdHF1ZXJ5aWQiO3M6NzoiOTcwMDcyNiI7czo5OiJOQ1NlYXJjaDMiO3M6MToiMSI7czo5OiJOQ1NlYXJjaDYiO3M6MToiMSI7czo5OiJOQ1NlYXJjaDciO3M6MToiMSI7czo5OiJOQ1NlYXJjaDgiO3M6MToiMSI7czo5OiJOQ1NlYXJjaDkiO3M6MToiMSI7czoxMDoiTkNTZWFyY2gxMiI7czoxOiIxIjtzOjEwOiJOQ1NlYXJjaDEzIjtzOjE6IjEiO3M6MTA6Ik5DU2VhcmNoMTQiO3M6MToiMSI7czoxMDoiTkNTZWFyY2gxNSI7czoxOiIxIjtzOjEwOiJOQ1NlYXJjaDE2IjtzOjE6IjEiO3M6MTA6Ik5DU2VhcmNoMTciO3M6MToiMSI7czoxOToiTnJDb2x1bW5zU29ydFNlYXJjaCI7czoyOiItMSI7czoxNToiT3JkZXJTb3J0U2VhcmNoIjtzOjE6Ik0iO3M6MTM6IkRlZkNvbDRTZWFyY2giO3M6MToiWSI7czoyMjoiTnVtYmVyT2ZGaW5kc0VtcHR5RGF0ZSI7czoyOiJObyI7fQ%3D%3D; ocdata=YTo0OntzOjY6InVzZXJpZCI7aTowO3M6ODoidXNlcm5hbWUiO3M6MDoiIjtzOjk6Imxhc3Rsb2dpbiI7czowOiIiO3M6OToic2Vzc2lvbmlkIjtzOjA6IiI7fQ%3D%3D; _gat=1; _ga=GA1.2.1992163183.1460800969; _ga=GA1.3.1991856598.1419972857
```

**Comment by kojoty** [comment]
kombinuję też czy te errory:
```
+++ PDO Error +++ 
+++ Debug: Query: insert into cache_rating(cache_id, user_id) values (49699,69730);
+++ Ex_Code: 23000
+++ Ex_Msg: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '49699-69730' for key 'PRIMARY'
+++ Ex_Trace:
#0 /var/www/ocpl/Utils/Database/XDb.php(140): PDOStatement->execute(Array)
#1 /var/www/ocpl/mobile/logentry.php(129): Utils\Database\XDb::xSql('insert into cac...')
#2 {main}
```

nie sa tez  z tym powiązane...
