### ISSUE TITLE
Countries list and per-node defaults...

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#578]
The source of the issue is DB error we got last days:
```
+++ PDO Error +++ 
+++ Debug: Query: SELECT `short` FROM `countries`
                        WHERE (`list_default_de`=1) AND (lower(`short`) = lower( ? ))
+++ Ex_Code: 42S22
+++ Ex_Msg: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'list_default_de' in 'where clause'
+++ Ex_Trace:
#0 /var/www/ocpl/Utils/Database/XDb.php(117): PDOStatement->execute(Array)
#1 /var/www/ocpl/editcache.php(581): Utils\Database\XDb::xSql('SELECT `short` ...', 'DE')
#2 {main}
```

It seems that at many places in the code we have a construction: list_default_$lang, which try to get defaults per node based on current selected language...

In my opinion the country list should be moved to static configuration in files, but before that at least $lang should checked by:
```
if (checkField('countries', 'list_default_' . $lang)) {
  $lang_db = $lang;
} else {
  $lang_db = "en";
}  
```

**Comment by wloczynutka** [comment]
This is very old issue. Source of problem is that some of translations, and some configuration were from begining stored in db. @harrieklomp and me, removed a lot of them, and moved to translation files (we moved mostly translations) - but many still stays and still generate problems.

**Comment by kojoty** [comment]
@wloczynutka - yeah! That's why I think we need a better solution to store configs and redesign things like that....

@andrixnet - and that's the good example where in - my opinion - we need something more than simple single "settings" file with $config[]...

**Comment by andrixnet** [comment]
@kojoty - I don't see why this would require to over complicate settings.

**Comment by kojoty** [comment]
Potentially affected tables:
- cache_size
- cache_status
- cache_type
- countries
- languages
- log_types
- waypoint_type

**Comment by andrixnet** [comment]
- cache_size --> deifinitions moved to lib/Objects/GeoCache/GeoCache.php. Should be implemented sitewide and then table removed.
- cache_status --> deifinitions moved to lib/Objects/GeoCache/GeoCache.php. Should be implemented sitewide and then table removed.
- cache_type --> deifinitions moved to lib/Objects/GeoCache/GeoCache.php. Should be implemented sitewide and then table removed.

- countries ==> name translations already in language files. Active country list already defined in settings. (is sort column still used?) Could/should be moved to code as an array or other form of static definition?

- languages ==> translations already in language files. Active language list already defined in settings. (is sort column still used?) Could/should be moved to code as an array or other form of static definition?

- log_types --> deifinitions moved to lib/Objects/GeoCache/GeoCacheLog.php. Should be implemented sitewide and then table removed.
- waypoint_type --> deifinitions moved to lib/Objects/GeoCache/Waypoint.php. Should be implemented sitewide and then table removed.

AFAIK the overall goal is to have all data structures and data definitions in the code, activate/deactivate selective features in settings and only keep user data in database.
