### ISSUE TITLE
SQL error from newlogs.php

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#684]
```
+++ PDO Error +++ 

+++ Debug: Query: SELECT cache_logs.id, cache_logs.cache_id AS cache_id,

                cache_logs.type AS log_type, cache_logs.date AS log_date, `cache_logs`.`encrypt` `encrypt`,

                cache_logs.user_id AS luser_id, cache_logs.text AS log_text,

                cache_logs.text_html AS text_html, caches.name AS cache_name,

                caches.user_id AS cache_owner, user.username AS user_name,

                caches.user_id AS user_id, user.user_id AS xuser_id,

                caches.wp_oc AS wp_name, caches.type AS cache_type,

                cache_type.icon_small AS cache_icon_small, log_types.icon_small AS icon_small,

                log_types.pl as pl,

                IF(ISNULL(`cache_rating`.`cache_id`), 0, 1) AS `recommended`,

                COUNT(gk_item.id) AS geokret_in, `PowerTrail`.`id` AS PT_ID,

                `PowerTrail`.`name` AS PT_name, `PowerTrail`.`type` As PT_type,

                `PowerTrail`.`image` AS PT_image

        FROM (cache_logs INNER JOIN caches ON (caches.cache_id = cache_logs.cache_id))

            INNER JOIN user ON (cache_logs.user_id = user.user_id)

            INNER JOIN log_types ON (cache_logs.type = log_types.id)

            INNER JOIN cache_type ON (caches.type = cache_type.id)

            LEFT JOIN `cache_rating` ON `cache_logs`.`cache_id`=`cache_rating`.`cache_id`

                AND `cache_logs`.`user_id`=`cache_rating`.`user_id`

            LEFT JOIN gk_item_waypoint ON gk_item_waypoint.wp = caches.wp_oc

            LEFT JOIN gk_item ON gk_item.id = gk_item_waypoint.id

                AND gk_item.stateid<>1 AND gk_item.stateid<>4

                AND gk_item.typeid<>2 AND gk_item.stateid !=5

            LEFT JOIN `powerTrail_caches` ON cache_logs.cache_id = `powerTrail_caches`.`cacheId`

            LEFT JOIN `PowerTrail` ON `PowerTrail`.`id` = `powerTrail_caches`.`PowerTrailId`  AND `PowerTrail`.`status` = 1

        WHERE cache_logs.deleted=0

            AND cache_logs.id IN ()

            AND cache_logs.cache_id=caches.cache_id

            AND caches.status<> 4 AND caches.status<> 5

            AND caches.status<> 6

        GROUP BY cache_logs.id

        ORDER BY cache_logs.date_created DESC

+++ Ex_Code: 42000

+++ Ex_Msg: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')

            AND cache_logs.cache_id=caches.cache_id

            AND caches.sta' at line 27

+++ Ex_Trace:

#0 /serve/www/oc_ro/oc_www/Utils/Database/OcDb.php(110): PDOStatement->execute()

#1 /serve/www/oc_ro/oc_www/newlogs.php(110): Utils\Database\OcDb->simpleQuery('SELECT cache_lo...')

#2 {main}
```

**Comment by andrixnet** [comment]
I got this via email from the server.
At first glance, the page newlogs.php works properly. (?)

**Comment by kojoty** [comment]
@andrixnet 
This is a specific issue and I fixed many errors like that - teh problem is in 
`AND cache_logs.id IN ()`

There are many places in the code when someone prepares some list of something (here cache_log ids) but forget that there are rare situations when this list is empty - and then we got such error...

There should be a check before the query and if list which is inserted to IN() is empty query should be modified (or something...).

I'll try to fix it in a free moment or you can deal with it yourself earlier.

**Comment by kojoty** [comment]
By the way - those bugs were present in the code for years but now new DB code generates errors and send email at every problem with DB query so we know about it...

**Comment by kojoty** [comment]
now it should be fixed...
